# Generated by Django 4.2.7 on 2025-12-03 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Access",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("attempt_no", models.IntegerField(primary_key=True, serialize=False)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
                ("feedback", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Attempt",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("noti_id", models.AutoField(primary_key=True, serialize=False)),
                ("send_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Notification",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                ("problem_id", models.AutoField(primary_key=True, serialize=False)),
                ("correct_answer", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("difficulty", models.CharField(max_length=6)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Problem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Receive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "Receive",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("resource_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("res_type", models.CharField(max_length=13)),
                ("uploaded_time", models.DateTimeField(auto_now_add=True)),
                (
                    "resource_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "Resource",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "ResourceTopic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                ("scenario_no", models.AutoField(primary_key=True, serialize=False)),
                ("scenario_description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Scenario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Send",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "Send",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "topic_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Topic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="admin",
                        serialize=False,
                        to="core.user",
                    ),
                ),
                ("admin_level", models.CharField(default="Standard", max_length=8)),
            ],
            options={
                "db_table": "Admin",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HaveTopic",
            fields=[
                (
                    "problem",
                    models.ForeignKey(
                        db_column="problem_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.problem",
                    ),
                ),
            ],
            options={
                "db_table": "Have_topic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mentor",
                        serialize=False,
                        to="core.user",
                    ),
                ),
                (
                    "expertise_area",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("problems_created", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Mentor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student",
                        serialize=False,
                        to="core.user",
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                ("total_problems_attempted", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Student",
                "managed": False,
            },
        ),
    ]
